pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Check out the source code from GitHub
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                // Use the Maven Wrapper to build and test the Spring Boot application
                dir('Spring_boot_begineer/ems-backend') {
                    sh './mvnw clean package'
                    sh './mvnw test'
                }
            }
        }

        // Add more stages as needed for additional tasks (e.g., integration tests)
    }

    post {
        success {
            // Notify about successful build and tests
            echo 'Build and tests were successful!'
        }
        failure {
            // Notify or handle build or test failures
            echo 'Build or tests failed!'
        }
    }
}
